import type { LucideIcon } from 'lucide-react'
import {
  AppWindow,
  Bot,
  BriefcaseBusiness,
  ClipboardList,
  Compass,
  Database,
  FileText,
  FlipHorizontal2,
  GitBranch,
  Image,
  Info,
  LayoutDashboard,
  LayoutTemplate,
  Layers,
  Map,
  MapPinned,
  Megaphone,
  Move,
  Network,
  PanelsTopLeft,
  PencilRuler,
  SlidersHorizontal,
  Table2,
  TrendingUp,
  UserRound,
  Workflow,
  Zap,
} from 'lucide-react'

export const iconMap: Record<string, LucideIcon> = {
  dashboard: LayoutDashboard,
  filter: SlidersHorizontal,
  bot: Bot,
  app: AppWindow,
  docs: FileText,
  form: ClipboardList,
  layers: Layers,
  image: Image,
  mappin: MapPinned,
  builder: PanelsTopLeft,
  zap: Zap,
  template: LayoutTemplate,
  strategy: Compass,
  business: BriefcaseBusiness,
  marketing: Megaphone,
  sales: TrendingUp,
  map: Map,
  sheet: Table2,
  lucid: Network,
  flip: FlipHorizontal2,
  bpmn: Workflow,
  graph: GitBranch,
  drag: Move,
  gds: Database,
  drawio: PencilRuler,
  account: UserRound,
  about: Info,
}

export const iconKeys = Object.keys(iconMap)

export function getIcon(name?: string): LucideIcon {
  return iconMap[name || ''] || LayoutDashboard
}
